// 한국어 명제 데이터
const SAVANT_DATA_KR = [
    "당신은 어제 {{유형}}과 밀담했다",
    "{{유형}}과 {{캐릭터}}가 {{N}}칸 만큼 떨어져 있다",
    "{{캐릭터}}가 참가중이다/아니다",
    "당신의 살아있는 이웃에 {{유형}}이 {{N}}명 있다",
    "당신이 건강한 {{캐릭터}}라면 이번 밤에 {{정보}}을/를 받았을 것이다",
    "취한사람이 있/없다",
    "광기에 걸린 참가자가 있/없다",
    "악마는 {{캐릭터}}다",
    "악마가 선택하지 않은 사람이 이번 밤에 죽었다",
    "참가중인 {{유형}} 중 {{캐릭터}}가 있다",
    "두 쌍둥이의 가까운 사이에 {{유형}}이 {{N}}명 있다",
    "현재 살아있는 {{유형/진영}}은 {{N}}명이다",
    "어제 낮, 악마가 {{지명/투표}}했다",
    "{{N}}번째 낮에 {{캐릭터}}가 지명했/당했다",
    "새로운 {{유형/캐릭터}}가 탄생했다",
    "{{유형/캐릭터}}의 살아있는 이웃에 {{유형}}이 있다",
    "인원 구성이 변경 되었다/되지 않았다",
    "당신의 살아있는 이웃에 중독/취한 사람이 있다",
    "{{유형}} 캐릭터가 직전 밤에 1회성 능력을 사용했다",
    "이번 게임에서 광기에 걸렸던 참가자 중 {{진영}}이 있다",
    "직전 밤에 캐릭터가 바뀐 참가자가 있다",
    "직전 밤에 진영이 바뀐 참가자가 있다",
    "오늘 낮에 능력을 사용한 참가자 중 틀린 정보를 받은 참가자가 있다",
    "직전 밤에 {{유형}}을 상대로 능력을 사용한 {{유형}}이 있다",
    "{{캐릭터/참가자}}는 직전 밤에 {{캐릭터/참가자}}를 선택했다",
    "직전 밤 모든 마을주민은 옳은 정보를 받았다",
    "직전 밤에 취하거나 중독됐지만 옳은 정보를 받은 참가자가 있다",
    "{{캐릭터}}와 {{캐릭터}} 중 하나가 참가 중이다",
    "{{유형/캐릭터/참가자}}은는 직전 밤에 {{캐릭터}}에게 선택 되었다",
    "가장 가까운 {{유형}} 과 {{유형}} 사이에 {{유형}}이 {{N}}명 있다",
    "{{유형}}의 이웃은 모두 {{유형}}이다",
    "{{의상}}을 입은/신은 사람 중 {{유형}} 이/가 있다",
    "직전 밤 {{N}}명의 선한 참가자가 밤에 일어났다",
    "직전 밤 {{캐릭터}}는 틀린 정보를 받았다",
    "가장 길게 나란히 앉은 {{진영}}참가자의 수는 {{N}}명이다",
    "{{캐릭터/악마}}는 죽었다",
    "게임을 시작할 때 보다, 지금 {{유형/악팀}}의 수가 더 많/적다",
    "당신의 현재 살아있는 이웃은 {{다른/같은/선/악}} 팀이다",
    "{{캐릭터}}는 이틀 밤 연속으로 같은 참가자를 선택했다",
    "현재 살아있는 악한 참가자의 수는 홀수/짝수 이다",
    "이번 게임에 인원 구성 기본 셋팅을 변경한 캐릭터가 존재한다",
    "{{N}}번째 밤에 악마는 이미 죽은 참가자를 선택했다",
    "현재까지 처형된 참가자는 모두 선팀이다",
    "직전 밤 {{N}}명의 참가자가 같은 참가자를 선택했다",
    "오늘 낮에 {{캐릭터/참가자}}를 지명한 참가자는 선/악팀이다",
    "현재 죽은 참가자 중, 악마가 죽인 참가자는 {{N}}명이다",
    "현재 악마는 밤에 1명 이상 죽일 수도 있다",
    "어제 공개적으로 자신의 캐릭터를 주장한 참가자 중, {{N}}명이 거짓말 했다",
    "직전 밤 {{N}}이라는 정보를 받은 참가자는 없다",
    "자신의 능력/캐릭터를 착각하고 있는 참가자가 있다",
    "이번 게임에 팀(진영)이 바뀔 수 있는 캐릭터는 존재하지 않는다",
    "직전 밤, 중독/취했지만 맞는 정보를 받은 참가자가 있다",
    "{{참가자}}부터 시계/반시계 방향으로 {{참가자}} 사이에 {{유형}}이 있다",
    "광기에 걸린 척 하는 참가자가 있다",
    "{{캐릭터/참가자}}의 정보는 틀렸다",
    "직전 낮에 사회자를 비밀스럽게 찾아온 참가자 중 {{캐릭터}}가 있/없다",
    "게임 중, {{유형}} 캐릭터가 다른 유형으로 바뀐 적이 있다",
    "직전에 서번트가 받은 명제는 둘 다 {{틀렸/맞}} 다",
    "당신은 어제 {{유형}}과 밀담했다",
    "현재 살아있는 N명의 참가자가 취하거나 중독되었다",
    "현재 모든 악팀이 살아있다",
    "{{캐릭터}} 와 {{캐릭터}} 중 하나만 참가 중이다",
    "직전 밤 캐릭터가 바뀐 참가자는 없다/있다",
    "수학자가 직전에 받은 정보엔 낮에 능력을 사용한 캐릭터는 포함되지 않았다",
    "올바른 정보를 받은 저글러는 없다",
    "지난 낮/밤에, 악마인 참가자가 {{단어/문장}}라고 말했다",
    "현재 {{유형}}의 살아있는 이웃중에 악팀이 있다",
    "{{캐릭터}}는 게임 시작할때는 참가중이지 않았다",
    "현재 악마의 살아있는 이웃은 같은 팀이다",
    "어제 서번트에게 제공한 명제는 둘 다 맞는/틀린 명제이다",
    "직전 밤 N명의 참가자가 (자신의)능력사용을 위해 일어났다",
    "{{유형}}과 가장 가까운 다른 {{유형}} 사이에 악마가 있다",
    "{{참가자}}는 {{주정뱅이/꼭두각시}}다",
    "어제 {{악마}}는 {{N}}번 투표했다",
    "{{참가자}}와 {{참가자}} 중 1명이 악한 진영이다",
    "직전 밤 미치광이와 악마는 서로 다른 참가자를 선택했다",
    "직전 밤 누군가가 능력 사용을 거부했다",
    "{{캐릭터}}와 {{캐릭터}} 중 하나는 악마의 블러프이다",
    "{{참가자}}는 직전 밤 올바른 정보를 받았다"
];

// 영어 명제 데이터
const SAVANT_DATA_EN = [
    "You had a private chat with a {{type}} yesterday",
    "A {{type}} and the {{character}} are {{N}} spaces apart",
    "The {{character}} is/isn't in play",
    "There are {{N}} {{type}} characters among your alive neighbours",
    "If you were a healthy {{character}}, you would have received {{info}} tonight.",
    "There is/is no drunk player",
    "There is/is no player who is mad",
    "The Demon is the {{character}}",
    "Someone not chosen by the Demon died tonight",
    "One of the {{type}} characters in play is the {{character}}",
    "There are {{N}} {{type}} characters between the two twins (shortest path)",
    "There are {{N}} alive {{type/alignment}} players currently",
    "The Demon {{nominated/voted}} yesterday",
    "On day {{N}}, the {{character}} {{nominated/was nominated}}",
    "A new {{type/character}} was created",
    "One of the {{type/character}}'s alive neighbours is a {{type}}",
    "The character counts (setup) have/have not been modified",
    "One of your alive neighbours is poisoned or drunk",
    "A {{type}} character used a once-per-game ability last night",
    "Among the players who have been mad this game, there is a {{alignment}} player",
    "A player changed characters last night",
    "A player changed alignment last night",
    "Among the players who used an ability today, someone received false information",
    "A {{type}} used their ability on a {{type}} last night",
    "The {{character/player}} chose the {{character/player}} last night",
    "All Townsfolk received true information last night",
    "A player who was drunk or poisoned last night received true information",
    "Either the {{character}} or the {{character}} is in play",
    "The {{type/character/player}} was chosen by the {{character}} last night",
    "There are {{N}} {{type}} characters between the closest {{type}} and {{type}}",
    "Both neighbours of the {{type}} are {{type}} characters",
    "Among those wearing {{item of clothing}}, there is a {{type}}",
    "Last night, {{N}} good players woke up",
    "The {{character}} received false information last night",
    "The longest sequence of consecutive {{alignment}} players is {{N}}",
    "The {{character/Demon}} is dead",
    "There are more/fewer {{type/evil team members}} now than at the start of the game",
    "Your current alive neighbours are on the {{different/same/good/evil}} team",
    "The {{character}} chose the same player two nights in a row",
    "The number of alive evil players is odd/even",
    "A character that modified the base setup is in play",
    "On night {{N}}, the Demon chose a dead player",
    "All players executed so far were on the good team",
    "Last night, {{N}} players chose the same player",
    "The player who nominated the {{character/player}} today is on the good/evil team",
    "Among the dead players, {{N}} were killed by the Demon",
    "The Demon can currently kill more than one player at night",
    "Among the players who publicly claimed a character yesterday, {{N}} lied",
    "No player received the information '{{N}}' last night",
    "A player is mistaken about their character or ability",
    "There are no characters in play that can change teams (alignment)",
    "A player who was poisoned or drunk last night received true information",
    "Between {{player}} and {{player}} (clockwise/counter-clockwise), there is a {{type}}",
    "A player is pretending to be mad",
    "The {{character/player}}'s information was false",
    "Among the players who visited the Storyteller privately today, there is/is no {{character}}",
    "A {{type}} character has changed to a different character type during the game",
    "Both statements the Servant received last time were {{false/true}}",
    "You had a private chat with a {{type}} yesterday",
    "{{N}} alive players are currently drunk or poisoned",
    "All members of the evil team are currently alive",
    "Only one of the {{character}} and the {{character}} is in play",
    "No player/A player changed characters last night",
    "The Mathematician's last piece of information did not include characters who used their abilities during the day",
    "No Juggler received true information",
    "The Demon said '{{word/sentence}}' during the last day/night",
    "There is an evil player among the {{type}}'s alive neighbours",
    "The {{character}} was not in play at the start of the game",
    "The Demon's alive neighbours are on the same team",
    "Both info provided to the Servant yesterday were true/false",
    "{{N}} players woke up last night to use their own ability",
    "The Demon is between a {{type}} and the closest other {{type}}",
    "{{player}} is the {{Drunk/Marionette}}",
    "The {{Demon}} voted {{N}} times yesterday",
    "One of {{player}} and {{player}} is evil",
    "The Lunatic and the Demon chose different players last night.",
    "Someone refused to use their ability last night",
    "Either the {{character}} or the {{character}} is a Demon bluff",
    "{{player}} received true information last night"

];
